In [ ]:
#variable
a=10
print("I am ",a,"years old")


I am  10 years old


In [ ]:
#arthmetic two integer variables
a=int(input("enter a number: "));
b=int(input("enter b mnumber: "));
print("sum is:",a+b)
print("Difference is:",a-b);
print("product is:",a*b);
print("Quotient is:",a/b);
print("remainder is:",a%b);
print("power is:",a**b);
print("Floor divisin is:",a//b);

enter a number: 4
enter b mnumber: 8
sum is: 12
Difference is: -4
product is: 32
Quotient is: 0.5
remainder is: 4
power is: 65536
Floor divisin is: 0


In [ ]:
#take the numbers from the user (salary) if the salary is more than 50k their is a 10% tax print his final salary
a=int(input("enter your salary:"))
if(a>=50000):
  print("salary is:",a-a*(0.1))
else:
        print(" your salary is less than 50k so ,no tax")

enter your salary:89
 your salary is less than 50k so ,no tax


In [ ]:
#Get the salary from the user if the salary is more than 50k apply 10% tax deduction if the salary is less than 50k apply if 5% tax if the salary is more  than 70k apply 12% tax if the salary exceeds 1l print your are pramoted to next level
a=int(input("enter your salary:"))
if(a>=100000):
  print("you are pramoted")
elif(a>=70000):
  print("12% tax is deducted",a-a*(0.12))
elif(a>=51000):
  print("10% tax is deducted",a-a*(0.1))
else:
  print("5% tax is deducted,salary:",a-a*(0.5))

enter your salary:45000
5% tax is deducted,salary: 22500.0


In [ ]:
#for loop
num=int(input("enter number:"))

for i in range(1,11,1):
  print(num,'x',i,'=',num*i)




enter number:100
100 x 1 = 100
100 x 2 = 200
100 x 3 = 300
100 x 4 = 400
100 x 5 = 500
100 x 6 = 600
100 x 7 = 700
100 x 8 = 800
100 x 9 = 900
100 x 10 = 1000


In [ ]:
a=int(input("enter number:"))
i=1
while(i<=10):
  print(a,"x",i,"=",a*i)
  i=i+1

enter number:9
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


In [ ]:
l1=[1,"ha",77.8,"k",22]
for i in l1:
  print(i)

1
ha
77.8
k
22


In [ ]:
l1.append("last") # adds element at back of the list
for i in l1:
  print(i)


1
ha
77.8
k
22
last


In [ ]:
l1.insert(3,"insered") #the value inserted into list at given index place
for i in l1:
  print(i)

1
ha
77.8
insered
k
22
last


In [ ]:
l2=["aaa",26,"bbb",79.8,'c']
l1.extend(l2) #list.extend(list2)
              #l1=l1+l2
for i in l1:
  print(i)

1
ha
77.8
insered
k
22
last
aaa
26
bbb
79.8
c
aaa
26
bbb
79.8
c


In [ ]:
l1.pop(0) #remove the element given index place
print(l1)
l1.remove(79.8) #remove the element given element name
print(l1)


['k', 'last', 'aaa', 26, 'bbb', 'c', 'aaa', 26, 'bbb', 79.8, 'c']
['k', 'last', 'aaa', 26, 'bbb', 'c', 'aaa', 26, 'bbb', 'c']


In [ ]:
l1.remove(79.8) #remove the element given element name
print(l1)

ValueError: list.remove(x): x not in list

In [ ]:
l1.clear()
print(l1)
l2.clear()
print(l2)


[]
[]


In [ ]:
# create a list of ranadom integers need 10 elements
l=[1,2,3,4,5,6,7,8,9,10]
m=[]
for i in l:

  m.append(i*i)
print(m)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#list comprehention
#newlist=[output for]
#newlist-[ooutput for if]
l5=[1,2,3,4,5]
m1=[i*i for  i in l5 if i>3]
print(m1)

[16, 25]


In [ ]:
#list comprehention
#newlist=[(st of if) if (cond) else (st of else)]
list=[23,67,12,34,69]
res=[i*i if i>50 else 'x' for i in list]
print(res)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#take the salary from the user if the salary is lessthan 50k 10% tax other wise 15%tax
n=[78000,50400,34000,23000,14000]
m=[(i-i*0.1) if i<50000 else (i-i*0.15) for i in n]
print(m)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#dictionary
dict1={1:"satish",2:"sriram",3:"tarun"}
print(dict1)

{1: 'satish', 2: 'sriram', 3: 'tarun'}


In [ ]:
print(dict1.keys())
print(dict1.values())



dict_keys([1, 2, 3])
dict_values(['satish', 'sriram', 'tarun'])


In [ ]:
dict1[2]

'sriram'

In [ ]:
dict3={"dept":"cse","details":{"year":"II","sec":"D","count":71}}
print(dict3)
print("year is: ",dict3["details"]["year"])
print("section is:",dict3["details"]["sec"])
print("count:",dict3["details"]["count"])

{'dept': 'cse', 'details': {'year': 'II', 'sec': 'D', 'count': 71}}
year is:  II
section is: D
count: 71


In [ ]:
dict4=[34,56,78,39,100]
names=["prem","tarun","sriram","kishore","ravi"]
new_zip=(zip(dict4,names))
for i in new_zip:
  print(i)

(34, 'prem')
(56, 'tarun')
(78, 'sriram')
(39, 'kishore')
(100, 'ravi')


In [ ]:
dict4=[34,56,78,39,100]
names=["prem","tarun","sriram","kishore","ravi"]
new_zip=dict(zip(dict4,names))
print(new_zip)

{34: 'prem', 56: 'tarun', 78: 'sriram', 39: 'kishore', 100: 'ravi'}


In [ ]:
import numpy as np
A=np.array([1,2,3,4]) #1D array
print(A.ndim)
print(A.shape)
print(A)

1
(4,)
[1 2 3 4]


In [ ]:
import numpy as np
B=np.array([[1,2,4],[3,5,4],[4,5,6]])#2D array
print(B.ndim)
print(B.shape)
print(B)

2
(3, 3)
[[1 2 4]
 [3 5 4]
 [4 5 6]]


In [ ]:
import numpy as np
c=np.array([[[2,3,4,],[4,5,6],[4,8,5]],[[3,3,5],[2,3,9],[3,5,5]]])#3D array
print(c.ndim)
print(c.shape)
print(c)

3
(2, 3, 3)
[[[2 3 4]
  [4 5 6]
  [4 8 5]]

 [[3 3 5]
  [2 3 9]
  [3 5 5]]]


In [ ]:
D=np.ones((5,3)) #g,r,c
print(D)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
D=np.zeros((2,3,4)) #g,r,c
print(D)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#print all the nu mbers divisible by 8 using range blw 1-1000
A=np.arange(8,1001,8)
print(A)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
#spliting A range into n numbers with comman differences
A=np.linspace(48,59,10)
print(A)

[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


In [ ]:
#tuples,sets,documentation,qrcodes,

In [1]:
#tupple
t=(1,2,3,5,8,9)
print(t)
print(t*2)
print(t[0])
print(t[-3])
print(t[1:4])

(1, 2, 3, 5, 8, 9)
(1, 2, 3, 5, 8, 9, 1, 2, 3, 5, 8, 9)
1
5
(2, 3, 5)


In [ ]:
t1=t+(4,7)
print(t1)

(1, 2, 3, 5, 8, 9, 4, 7)


In [ ]:
count=t1.count(3)
print(count)

1


In [ ]:
#sets
s={1,2,3,6,8,9}
s.add(7)
print(s)

{1, 2, 3, 6, 7, 8, 9}


In [ ]:
s.remove(9)
print(s)

{1, 2, 3, 6, 7, 8}


In [ ]:
union=s.union({6,9,4})
print(union)

{1, 2, 3, 4, 6, 7, 8, 9}


In [ ]:
insert=s.intersection({1,3,5})
print(insert)

{1, 3}


In [ ]:
diff=s.difference({1,2,3,4})
print(diff)

{8, 6, 7}


In [ ]:
#checking condition true or falseS
check=4 in s
check2=6 in s
print(check)
print(check2)

False
True


In [2]:
a=[8,6,7,12,3,5]
a.sort()
print(a)

[3, 5, 6, 7, 8, 12]


In [4]:
a=[8,6,7,12,3,5]
b=sorted(a)
print(b)

[3, 5, 6, 7, 8, 12]


In [7]:
import numpy as np
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
