In [ ]:
a=[8,6,7,12,3,5]
a.sort()
print(a)

[3, 5, 6, 7, 8, 12]


In [ ]:
A=np.linspace(20,40,12).reshape(2,6)
print(A)

[[20.         21.81818182 23.63636364 25.45454545 27.27272727 29.09090909]
 [30.90909091 32.72727273 34.54545455 36.36363636 38.18181818 40.        ]]


In [ ]:
B=np.array([45,33,23,67,88,77,65,98]).reshape(2,2,2)
print(B)
#reshape-changes needs saving in another variable

[[[45 33]
  [23 67]]

 [[88 77]
  [65 98]]]


In [ ]:
B=np.array([45,33,23,67,88,77,65,98])
B.resize(2,2,2)  #resize-changes the shape of original array
print(B)

[[[45 33]
  [23 67]]

 [[88 77]
  [65 98]]]


In [ ]:
A=np.array([34,56,78,90])
B=np.array([7,9,3,12])#list will throw an error while arrays iterate themselves
c=A-B
print(c)

[27 47 75 78]


In [ ]:
A=np.array([34,56,78,90])
B=np.array([7,9,3,12])#list will throw an error while arrays iterate themselves
c=A+B
print(c)

[ 41  65  81 102]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-________________________________")
print(B)
print("-________________________________")
c=A*B  #one or one multiplication
print(c)

[[34 56]
 [78 90]]
-________________________________
[[ 7  9]
 [ 3 12]]
-________________________________
[[ 238  504]
 [ 234 1080]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-________________________________")
print(B)
print("-________________________________")
c=A@B  #matrix multiplication
print(c)

[[34 56]
 [78 90]]
-________________________________
[[ 7  9]
 [ 3 12]]
-________________________________
[[ 406  978]
 [ 816 1782]]


In [ ]:
A=np.array([25.4,33,44.4,55.4,99.99,99])
print(A.max())#max and min only accepts numeric and float datatypes
print(A.min())

99.99
25.4


In [ ]:
A=np.array([34,56,78,90,16,23,57,78]).reshape(4,2)
print(A)
print("-________________________________")
print(A.max(axis=0))#axis 0 -column wise
print("_________________________________")
print(A.max(axis=1))#axis 1- row wise

[[34 56]
 [78 90]
 [16 23]
 [57 78]]
-________________________________
[78 90]
_________________________________
[56 90 23 78]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-________________________________")
print(B)
print("After vertically stacking the arrays")
print(np.vstack((A,B)))



[[34 56]
 [78 90]]
-________________________________
[[ 7  9]
 [ 3 12]]
After vertically stacking the arrays
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-________________________________")
print(B)
print("After horizontal stacking the arrays")
print(np.hstack((A,B)))

[[34 56]
 [78 90]]
-________________________________
[[ 7  9]
 [ 3 12]]
After horizontal stacking the arrays
[[34 56  7  9]
 [78 90  3 12]]


In [ ]:
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("-________________________________")
print(B)
print("After  stacking the arrays")
print(np.stack((A,B),axis=0))#vertical stack
print("-________________________________")
print(np.stack((A,B),axis=1))#horizontal

[[34 56]
 [78 90]]
-________________________________
[[ 7  9]
 [ 3 12]]
After  stacking the arrays
[[[34 56]
  [78 90]]

 [[ 7  9]
  [ 3 12]]]
-________________________________
[[[34 56]
  [ 7  9]]

 [[78 90]
  [ 3 12]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))# no. of rows --->no.of groups
#no.of col in every group--> no.of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After stack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting array
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting array
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting array
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(1,3,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting array
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.hsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#splitting array
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
A=np.arange(21,39).reshape(3,6)
print(A)
print(A.argmax())


[[21 22 23 24 25 26]
 [27 28 29 30 31 32]
 [33 34 35 36 37 38]]
17


A = np.arange(18).reshape(3,6)
print(A)
print(A.argmax(axis = 0))# returns maximum number in each column
print(A.argmax(axis = 1))#returns maximumn number in each row

In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmax(axis = 0))# returns maximum number in each column
print(A.argmax(axis = 1))#returns maximumn number in each row

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[2 2 2 2 2 2]
[5 5 5]


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmin())# positions[0 0 0 0 0 0
                             # 1 1 1 1 1 1
                              #2 2 2 2 2 2
                              #3 3 3 3 3 3]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
0


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmin(axis = 0))
print(A.argmin(axis = 1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[0 0 0 0 0 0]
[0 0 0]


In [ ]:
A = np.array([17,4,18,56,12,33,89,21,34,1,11,13])
print(A)
print(A.argmin())# returns minimum number in the array


[17  4 18 56 12 33 89 21 34  1 11 13]
9


In [ ]:
#mean,median,std,var
A=np.array([12,34,25,66,71,88])
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Variance:",np.var(A))
print("Standard dev:",np.std(A))

Mean: 49.333333333333336
Median: 50.0
Variance: 743.888888888889
Standard dev: 27.274326552435515


In [ ]:
#trigonometry
A=np.pi
print(A)

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(A)
print(np.rad2deg(A))#convert radians to degrees

[0.78539816 1.04719755 1.57079633 3.14159265]
[ 45.  60.  90. 180.]


In [ ]:
B=np.array([0,30,45,60,90,120,180])
print(np.deg2rad(B))#covert degrees to radians

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(B)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(B)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(B)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)#sin^-1

1.5707963267948966

In [ ]:
np.arccos(1) #cos^-1

0.0

In [ ]:
np.arctan(1)#tan^-1

0.7853981633974483

In [ ]:
print(np.sin(B))
print(np.cos(B))
print(np.tan(B))
print(np.arcsin(B))#sin^-1
print(np.arccos(B))#cos^-1
print(np.arctan(B))#tan^-1

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
 -0.59846007]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301
  1.33869021]
[ 0. nan nan nan nan nan nan]
[1.57079633        nan        nan        nan        nan        nan
        nan]
[0.         1.53747533 1.54857776 1.5541312  1.55968567 1.56246319
 1.56524083]


<ipython-input-100-a5d19856b72d>:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(B))#sin^-1
<ipython-input-100-a5d19856b72d>:5: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(B))#cos^-1


In [ ]:
#searching an element
A=np.array([90,3,45,21,34,90,21])
print(np.where(A==21))#returns index positions

(array([3, 6]),)


In [ ]:
a=8
b=6
print(np.hypot(a,b))

10.0


In [ ]:
#searching an element
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))#returns index positions

(array([0, 4, 5]),)


In [ ]:
#searching an element
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>25))#returns index positions

(array([0, 2, 4, 5]),)


In [2]:
#read an array with elements serching sorted
import numpy as np
A=np.array([1,23,2,34,90,21])
print(np.searchsorted(A,34))#outputs the index of a sorted element



3


In [8]:
#linear algebra and ufunc
import numpy as np
A=np.array([1,23,2,34,90])
B=np.array([3,4,5,7,8])
print(np.add(A,B))
print(np.subtract(A,B))

[ 4 27  7 41 98]
[-2 19 -3 27 82]


In [9]:
print(np.divide(A,B))#dividng two arrays

[ 0.33333333  5.75        0.4         4.85714286 11.25      ]


In [10]:
print(np.mod(A,B))#Modulus of two numbers

[1 3 2 6 2]


In [11]:
print(np.divmod(A,B))

(array([ 0,  5,  0,  4, 11]), array([1, 3, 2, 6, 2]))


In [13]:
B=np.array([3,4,5,7,8])
print(np.diff(B))

[1 1 2 1]


In [14]:
B=np.array([3,4,5,2,1,8])
print(np.sort(B))

[1 2 3 4 5 8]


In [16]:
A=np.array([23,45,35,66,77])
B=np.array([24,46,57,88,11])
print(np.union1d(A,B))

[11 23 24 35 45 46 57 66 77 88]


In [18]:
A=np.array([23,45,35,66,77])
B=np.array([24,45,57,88,11])
print(np.setdiff1d(A,B))

[23 35 66 77]


A=np.array([23,45,35,88,77])
B=np.array([24,45,57,88,11])
print(np.intersect1d(A,B))


In [21]:
#ROUNDING
import numpy as np
a1=np.trunc([-3.1666,36667])
print(a1)

[-3.0000e+00  3.6667e+04]


In [22]:
#ROUNDING
import numpy as np
a1=np.fix([-3.1666,36667])
print(a1)

[-3.0000e+00  3.6667e+04]


In [23]:
#ROUNDING
import numpy as np
a1=np.around([-3.1666,36667])
print(a1)

[-3.0000e+00  3.6667e+04]


In [24]:
#ROUNDING
import numpy as np
a1=np.floor([-3.1666,36667])
print(a1)

[-4.0000e+00  3.6667e+04]


In [25]:
#ROUNDING
import numpy as np
a1=np.ceil([-3.1666,36667])
print(a1)

[-3.0000e+00  3.6667e+04]


In [26]:
import numpy as np
print(np.around(3.16626,4))
print(np.trunc([-3.1666,3.6666]))
print(np.fix([-3.1666,3.6666]))
print(np.floor([-3.1666,3.6666]))
print(np.ceil([-3.1666,3.1]))

3.1663
[-3.  3.]
[-3.  3.]
[-4.  3.]
[-3.  4.]


**More functions**

In [28]:
A=np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [32]:
A=np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [35]:
print(np.lcm(34,56))
print(np.gcd(455,665))

952
35


In [37]:
Ar=np.array([45,65,30])
print(np.gcd.reduce(Ar))

5


In [38]:
Ar=np.array([45,65,30])
print(np.lcm.reduce(Ar))

1170


In [39]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [40]:
from numpy import random as rd


In [46]:
A=rd.randint(4)
print(A)

2


In [51]:
A=rd.randint(50,size=6)#limit
print(A)

[18 10 22 12 47  5]


In [52]:
A=rd.randint(50,size=(2,3))#row and column arrange in random
print(A)

[[ 4 23 27]
 [ 9 10 29]]


In [53]:
A=np.array([1,2,3])
B=np.array([4,5,6])#(1*4+2*5+3*6)
print(np.inner(A,B))

32


In [54]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.outer(A,B))


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [55]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))

[-3  6 -3]
